"""Generate JSON Schema and TypeScript wire contracts from Pydantic models.

Run from the repository root with ``uv run python scripts/generate_contracts.py``.
The TypeScript compiler is the pinned ``json-schema-to-typescript`` package from
the frontend development dependencies.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

from metis_sim.domain.config import SimulationConfig
from metis_sim.domain.public import (
    ControlRequest,
    OrbitPoint,
    PublicLimit,
    PublicRunStatus,
    PublicSpacecraft,
    SatelliteTrajectory,
    SequenceRange,
    Snapshot,
    Trajectory,
    ViewerBootstrap,
    VisualMessage,
)
from metis_sim.domain.telemetry import ChannelReading, MeasurementFrame, OperationalEvent
from pydantic import BaseModel
from pydantic.json_schema import JsonSchemaMode

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = ROOT / "schemas"
TS_OUTPUT = ROOT / "frontend/src/api/generated.ts"
MODELS: dict[str, tuple[type[BaseModel], JsonSchemaMode]] = {
    "SimulationConfig": (SimulationConfig, "validation"),
    "MeasurementFrame": (MeasurementFrame, "serialization"),
    "OperationalEvent": (OperationalEvent, "serialization"),
    "ChannelReading": (ChannelReading, "serialization"),
    "PublicLimit": (PublicLimit, "serialization"),
    "PublicSpacecraft": (PublicSpacecraft, "serialization"),
    "PublicRunStatus": (PublicRunStatus, "serialization"),
    "Snapshot": (Snapshot, "serialization"),
    "OrbitPoint": (OrbitPoint, "serialization"),
    "SatelliteTrajectory": (SatelliteTrajectory, "serialization"),
    "Trajectory": (Trajectory, "serialization"),
    "SequenceRange": (SequenceRange, "serialization"),
    "VisualMessage": (VisualMessage, "serialization"),
    "ViewerBootstrap": (ViewerBootstrap, "serialization"),
    "ControlRequest": (ControlRequest, "validation"),
}


def _schema(model: type[BaseModel], title: str) -> dict[str, Any]:
    """Return a named validation schema generated by the Pydantic model."""
    result = model.model_json_schema(mode="validation", ref_template="#/$defs/{model}")
    result["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    result["$id"] = f"https://metisorbital.local/schemas/{title}.json"
    result["title"] = title
    return result


def _draft7_tuple_compatibility(value: Any) -> Any:
    """Translate fixed tuple schemas for the TypeScript compiler's draft-07 subset."""
    if isinstance(value, list):
        return [_draft7_tuple_compatibility(item) for item in value]
    if not isinstance(value, dict):
        return value
    result = {key: _draft7_tuple_compatibility(item) for key, item in value.items()}
    if "prefixItems" in result:
        result["items"] = result.pop("prefixItems")
        result["additionalItems"] = False
    return result


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    """Write stable, readable generated JSON artifacts."""
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n")


def main() -> None:
    """Generate public JSON Schemas and compile the TypeScript contracts."""
    SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    individual = {
        "simulation.v1.schema.json": _schema(SimulationConfig, "simulation.v1"),
        "telemetry.v1.schema.json": _schema(MeasurementFrame, "telemetry.v1"),
        "operational_event.v1.schema.json": _schema(OperationalEvent, "operational_event.v1"),
    }
    for filename, schema in individual.items():
        _write_json(SCHEMA_DIR / filename, schema)

    definitions: dict[str, Any] = {}
    roots: dict[str, Any] = {}
    for name, (model, mode) in MODELS.items():
        model_schema = model.model_json_schema(mode=mode, ref_template="#/$defs/{model}")
        definitions.update(model_schema.pop("$defs", {}))
        if mode == "serialization":
            model_schema["required"] = list(model.model_fields)
        definitions.setdefault(name, model_schema)
        roots[name] = {"$ref": f"#/$defs/{name}"}
    for name, (model, mode) in MODELS.items():
        if mode == "serialization" and name in definitions:
            definitions[name]["required"] = list(model.model_fields)
    public_schema: dict[str, Any] = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "https://metisorbital.local/schemas/public-api.v1.json",
        "title": "MetisPublicContracts",
        "type": "object",
        "properties": roots,
        "required": list(roots),
        "additionalProperties": False,
        "$defs": definitions,
    }
    public_schema = _draft7_tuple_compatibility(public_schema)
    _write_json(SCHEMA_DIR / "public-api.v1.schema.json", public_schema)

    TS_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    command = [
        "npx",
        "--no-install",
        "json-schema-to-typescript",
        str(SCHEMA_DIR / "public-api.v1.schema.json"),
        "--output",
        str(TS_OUTPUT),
        "--cwd",
        str(ROOT / "frontend"),
        "--bannerComment",
        "/* Generated from Pydantic v2 contracts. Do not edit by hand. */",
    ]
    subprocess.run(command, check=True, cwd=ROOT / "frontend")


if __name__ == "__main__":
    main()
